"""AgroClima1.1-6

Revision ID: 1073a2a48712
Revises: 7c08d09387ba
Create Date: 2024-05-21 00:02:52.621136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1073a2a48712'
down_revision: Union[str, None] = '7c08d09387ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('user', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('roles', sa.Column('rolesty', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_constraint('roles_rolesty_id_fkey', 'roles', type_='foreignkey')
    op.drop_constraint('roles_user_id_fkey', 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'rolesty', ['rolesty'], ['id'])
    op.create_foreign_key(None, 'roles', 'user', ['user'], ['id'])
    op.drop_column('roles', 'user_id')
    op.drop_column('roles', 'rolesty_id')
    op.add_column('user', sa.Column('roles', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_foreign_key(None, 'user', 'roles', ['roles'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'roles')
    op.add_column('roles', sa.Column('rolesty_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key('roles_user_id_fkey', 'roles', 'user', ['user_id'], ['id'])
    op.create_foreign_key('roles_rolesty_id_fkey', 'roles', 'rolesty', ['rolesty_id'], ['id'])
    op.drop_column('roles', 'rolesty')
    op.drop_column('roles', 'user')
    # ### end Alembic commands ###
