"""AgroClima1.1-1

Revision ID: 3b62d4d18df1
Revises: 26f01da36cbf
Create Date: 2024-05-07 12:11:18.389901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b62d4d18df1'
down_revision: Union[str, None] = '26f01da36cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plags', sa.Column('recomenda', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('plags', 'recom')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plags', sa.Column('recom', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('plags', 'recomenda')
    # ### end Alembic commands ###
