"""AgroClima1.1-4

Revision ID: 49c0dbae2f4e
Revises: 49443e199e47
Create Date: 2024-05-20 19:36:43.260955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c0dbae2f4e'
down_revision: Union[str, None] = '49443e199e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'plags', ['id'])
    op.create_unique_constraint(None, 'plagsxplants', ['id'])
    op.create_unique_constraint(None, 'plantas', ['id'])
    op.create_unique_constraint(None, 'plantas_cat', ['id'])
    op.create_unique_constraint(None, 'plants_mp', ['id'])
    op.create_unique_constraint(None, 'recordcui', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'rolesty', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'rolesty', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'recordcui', type_='unique')
    op.drop_constraint(None, 'plants_mp', type_='unique')
    op.drop_constraint(None, 'plantas_cat', type_='unique')
    op.drop_constraint(None, 'plantas', type_='unique')
    op.drop_constraint(None, 'plagsxplants', type_='unique')
    op.drop_constraint(None, 'plags', type_='unique')
    # ### end Alembic commands ###
